before:
  hooks:
    - go mod download
    - go generate ./...

builds:
  - main: ./main.go
    id: "hw"
    binary: hw
    goos:
      - linux
      - darwin
    goarch:
      - amd64

archives:
  - format: tar.gz
    files:
      - LICENSE
      - README.md
      - CHANGELOG.md

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

nfpm:
  name: hw
  arch: amd64
  platform: linux
  version: v0.1.0
  prerelease: alpha
  section: default
  priority: extra
  description: |
    Hello World Package!
  license: "Apache 2.0"
  maintainer: "Gaius <gaius.qi@gmail.com>"
  homepage: https://qiwenbo.com

  replaces:
    - hw
  provides:
    - hw

  contents:
    - src: ./bin/hw
      dst: /usr/local/bin/hw
